#!/bin/bash

NAME=twon-agents
DIR=/home/ubuntu/apis/TWON-Agents
USER=ubuntu
GROUP=ubuntu
WORKERS=1
WORKER_CLASS=uvicorn.workers.UvicornWorker
TIMEOUT=180
VENV=.venv/bin/activate
BIND=unix:$DIR/api/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn api:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --timeout $TIMEOUT \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-

